### ISSUE TITLE
Rework to enable skipped test in FFmpegCommand

### ISSUE THREAD

**Issue by nihonjinrxs** [tedconf/fessonia#7]
The [skipped test](https://github.com/tedconf/ffmpeg-filtergraph/blob/master/test/ffmpeg_command.test.js#L56) in `FFmpegCommand`'s tests needs to be enabled. Not sure the best way to test that the library has generated a warning.

**Comment by bog** [comment]
Is this still true?

**Comment by nihonjinrxs** [comment]
This was done a while ago, and there's no longer a skipped test there. Closing.
